# 01-bug-report.yml for sphinx-cookiecutter
#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
name: 🐞 Bug Report
description: File a bug report for this template.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - jcook3701
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us fix it.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen vs what actually happened?
      placeholder: Describe the error here...
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running cookiecutter on?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    id: cc-version
    attributes:
      label: Cookiecutter Version
      description: Run 'cookiecutter --version' and paste the output.
      placeholder: e.g. 2.6.0
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or Error Message
      description: Please copy and paste the traceback or error message here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement
      options:
        - label: I have checked the existing issues for similar reports.
          required: true
