source 'https://rubygems.org'

# Core Dependencies
gem "faraday", "~> 2.14"
gem "faraday-retry", "~> 2.3"
gem "jekyll", "~> 4.4"
gem "just-the-docs", "~> 0.11"

gem "bigdecimal"
gem "csv"
gem "logger"
gem "base64"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-include-cache"
  gem "jekyll-github-metadata"
  gem "jekyll-remote-theme"
  gem "jekyll-redirect-from"
end
